# Generated by Django 5.0.4 on 2024-05-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product_images/images'),
        ),
    ]
