# Generated by Django 5.0.4 on 2024-05-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
